info:
  component: Config Server

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ajayanthony/movie_ticket_booking_system/
          searchPaths: config_repo

server:
  port: 8071