info:
  component: Config Server

spring:
  application:
    name: configserver
  profiles:
    active:
      - native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config_repo

server:
  port: 8071