server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

spring:
  cloud:
#    loadbalancer.ribbon.enabled: false
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
        - id: movies_service
          uri: lb://movies-service
          predicates:
            - Path=/movies/**
        - id: booking_service
          uri: lb://booking-service
          predicates:
            - Path=/booking/**
        - id: user_service
          uri: lb://user-service
          predicates:
            - Path=/user/**
      #      default-filters:
      #        - PrefixPath= /api

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
